### ISSUE TITLE
r['code']不等于0的时候也要将r['var']处理一下

### ISSUE THREAD

**Issue by xinxjxjxj** [tonglei100/injson#3]
https://github.com/tonglei100/injson/blob/f3eac0443e8c14364b345cc94e89caa5ebc9870b/injson.py#L155

r['code']不等于0的时候也要将r['var']处理一下，不然r['var']值就丢了

**Comment by tonglei100** [comment]
对于 r['var']，只有当 re['code'] 为 0 时，我们才认为是匹配到的，不为 0 时就不是我们想要的
